name: Terraform Plan
on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required to checkout code

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::541673202339:role/github-actions-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}" \
            -backend-config="key=vprofile/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"
            
      - name: Terraform Plan
        run: terraform plan